version: '3'

volumes:
  bundle: 
    driver: local

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: uaI7m2kmWd949DMv4dCh

  app:
    environment:
      PGPASSWORD: uaI7m2kmWd949DMv4dCh
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [setup/entry]
    volumes:
      - .:/refugerestrooms
      - /refugerestrooms/node_modules
      - bundle:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
